### ISSUE TITLE
Edit proxyList.txt

### ISSUE THREAD

**Issue by Leonidus0x10** [39ff/docker-rotating-proxy#14]
what file do i add my proxies to? do i have to add the proxies to the list and then run the docker-compose? or do i have to attach to a container and modify the list? please help

**Comment by 39ff** [comment]
>what file do i add my proxies to?

proxyList.txt

>do i have to add the proxies to the list and then run the docker-compose? 

yes

**Comment by Leonidus0x10** [comment]
> > what file do i add my proxies to?
> 
> proxyList.txt
> 
> > do i have to add the proxies to the list and then run the docker-compose?
> 
> yes
> 
> This repository simply generates the docker-compose.yml and squid config.

okay awesome, thank you! its a really awesome project.
