### ISSUE TITLE
Is there a way to view logs of requests

### ISSUE THREAD

**Issue by 123bistami** [39ff/docker-rotating-proxy#17]
Hello,

thank you for sharing your work. Is there a way to view proxy request log, e.g. response code 200,403. 

BR

**Comment by 39ff** [comment]
please check docker logs command
https://docs.docker.com/engine/reference/commandline/logs/
```
docker logs YOUR_CONTAINER_NAME

Example
docker logs dockersquid_rotate
docker logs dockersquid_rotate -f
```
