### ISSUE TITLE
New Lists?

### ISSUE THREAD

**Issue by Protektor-Desura** [39ff/docker-rotating-proxy#21]
I was wondering if you ever thought about supporting multiple lists automatically or using a script that could pull multiple lists automatically in to your setup.

https://github.com/clarketm/proxy-list

or

https://github.com/fate0/proxylist/

which uses this to create his list.
https://github.com/fate0/getproxy

Which pulls from the following lists.
http://www.cnproxy.com/
http://www.cool-proxy.net/
https://free-proxy-list.net/
http://www.ip181.com/
http://proxy-list.org/english/index.php
http://api.xicidaili.com/free2016.txt
http://static.fatezero.org/tmp/proxy.txt
http://pubproxy.com/api/proxy?limit=20&format=txt&type=http
http://comp0.ru/downloads/proxylist.txt
http://www.proxylists.net/http_highanon.txt
http://www.proxylists.net/http.txt
http://ab57.ru/downloads/proxylist.txt
https://www.rmccurdy.com/scripts/proxy/good.txt
http://www.xicidaili.com/nn/
http://www.xicidaili.com/wt/

**Comment by 39ff** [comment]
We have no plans to actively adopt public proxies as they are unstable and can become unusable in a very short period of time. 
We recommend using the HTTP proxy that comes with VPN services where you can access a large number of IP addresses for a small fee.
