### ISSUE TITLE
Enable Delegate SOCKS5 Proxy

### ISSUE THREAD

**Issue by uBadRequest** [39ff/docker-rotating-proxy#3]
I have an application that I want to rotate socks5 proxies for, i've been trying to modify your configuration to get it to work. Keep getting 502 errors. Any ideas?

**Comment by 39ff** [comment]
Hi.
Updated README.md and any files.
Please see Example2
https://github.com/39ff/docker-rotating-proxy/blob/master/README.md#proxylisttxt-example2
