### ISSUE TITLE
SurfShark?

### ISSUE THREAD

**Issue by ValiDrv** [39ff/docker-rotating-proxy#7]
Hello

I see this works with NordVPN, doesit also work with SurfShark VPN?

**Comment by 39ff** [comment]
Hi.
I checked SurfShark VPN

## shadowsocks
surfshark is not available as it only supports aes-256-gcm.
gost is not supported.😭
Support for shadowsocks is based on library shadowsocks-go.
-> method          encryption method, null by default (table), the following methods are supported:
                    aes-128-cfb, aes-192-cfb, aes-256-cfb, bf-cfb, cast5-cfb, des-cfb, rc4-md5, rc4-md5-6, chacha20, salsa20, rc4, table
https://github.com/ginuerzh/gost/blob/master/README_en.md#shadowsocks


## http/socks proxy?
>The only HTTPS proxy that we have is the Chrome or Firefox extension.
😭


Uh.. I'm testing the connection in other ways.

**Comment by 39ff** [comment]
hi.

it wokrs. 

proxyList.txt
```
se-sto.prod.surfshark.com:YOUR_PORT:ss2:AEAD_AES_256_GCM:YOUR_PASSWORD
```

**Comment by 39ff** [comment]
openvpn supported. try it.
https://github.com/39ff/docker-rotating-proxy/tree/master/openvpn

**Comment by ValiDrv** [comment]
Great, thank you. Now only if I could run it...

I like the idea, but it should be easier to get started, without the PHP file writing the docker-compose file.

Maybe something like: `docker run -d -p [auto rotate port] ... 39ff/docker-rotating-proxy`
Or your docker-compose.yml which has those ports and credentials, with one run command.
Check out: _mattes/rotating-proxy_, something similar to that.

**Comment by 39ff** [comment]
Yeah.. Exactly :)
